# 1. Úkoly

## 1.1 `ndarray`

1. Jak zjistit velikost paměti libovolného pole? Vyzkoušejte na `a = np.array([1, 2, 3])`. Otestujte různé datové typy (`dtype`), například `np.int32`, `np.float64`, `np.complex128`.


In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
print(np.array([1, 2, 3], dtype=np.int32).nbytes)
print(np.array([1, 2, 3], dtype=np.float64).nbytes)
print(np.array([1, 2, 3], dtype=np.complex128).nbytes)

12
24
48


2. Zjistěte počet rozměrů, velikosti v jednotlivých rozměrech a celkový počet prvků v poli `a`.


In [4]:
print(a.ndim)
print(a.shape)
print(a.size)

1
(3,)
3


3. Zjistěte typ prvků v poli `a` a velikost jednoho prvku v bajtech.


In [5]:
print(a.dtype)
print(a.itemsize)

int64
8


4. Vytvořte NumPy pole `b` se stejnými rozměry jako `a`, ale s typem `np.float32`.


In [6]:
b = np.empty_like(a, dtype=np.float32)

5. Přetypujte pole `a` na `np.float32` a uložte výsledek do pole `c`.


In [7]:
c = a.astype(np.float32)

6. Vytvořte pole `d` s typem `np.datetime64` a uložte do něj datum `"2023-12-01"`.


In [8]:
d = np.datetime64("2023-12-01")

7. Vytvořte pole `e` se složeným typem ze dvou sloupců: `int32` a `string_` s maximální délkou 10 znaků.


In [9]:
e = np.dtype([
    ('cele_cislo', np.int32),
    ('text', 'S10')
])

8. Naplňte pole `e` hodnotami `[(1, "a"), (2, "b"), (3, "c")]`.


In [10]:
e = np.array([(1, "a"), (2, "b"), (3, "c")], dtype=e)

9. Změňte hodnotu druhého prvku ve druhém sloupci pole `e` na `"hello"`.


In [11]:
e[1]['text'] = 'hello'
print(e)

[(1, b'a') (2, b'hello') (3, b'c')]


## 1.2 Vytváření polí

1. Vytvořte matici samých jedniček o rozměrech 3x3 a vypište všechny její prvky.


In [12]:
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


2. Vytvořte vektor s hodnotami od 10 do 49.


In [13]:
vector = np.arange(10, 50)

3. Vytvořte pole 3x4 typu `bool` se všemi prvky `True`.


In [16]:
pole = np.ones((3, 4), dtype=bool)
print(pole)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


4. Vytvořte matici 3x3 s hodnotami od 0 do 8.


In [23]:
A = np.arange(0, 9)
A = A.reshape((3, 3))
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


5. Vytvořte jednotkovou matici 3x3.


In [24]:
I  = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


6. Vytvořte pole 3x3x3 s náhodnými hodnotami.


In [1]:
import random as rd

In [28]:
rand = np.random.random((3, 3, 3))
print(rand)

[[[0.27001986 0.01629929 0.1276473 ]
  [0.43617522 0.71667887 0.17176465]
  [0.39910044 0.81725109 0.04419123]]

 [[0.28458179 0.54932395 0.76930143]
  [0.39396122 0.32921142 0.72633092]
  [0.46456744 0.06393425 0.06245639]]

 [[0.63934148 0.50196571 0.8933942 ]
  [0.28541615 0.16166597 0.18008049]
  [0.06388611 0.99204536 0.46723395]]]


7. Vytvořte 2D pole s 1 na okraji a 0 uvnitř.


In [6]:
array = np.ones((4, 4))
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


8. Jak přidat okraj vyplněný nulami kolem existujícího pole?


In [8]:
pad_array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print(pad_array)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


9. Vytvořte matici 5x5, kde jediné nenulové prvky jsou `[1, 2, 3, 4]` pod hlavní diagonálou (nápověda: `diagflat`).
```
0 0 0 0 0
1 0 0 0 0
0 2 0 0 0
0 0 3 0 0
0 0 0 4 0
```


In [9]:
matice = np.diagflat([1, 2, 3, 4], k=-1)
print(matice)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


10. Z pole 8x8 samých nul vytvořte pomocí řezů co nejelegantněji šachovnicovou matici 8x8.
```
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
```


In [10]:
chess = np.zeros((8, 8))
chess[1::2, ::2] = 1
chess[::2, 1::2] = 1
print(chess)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


11. Vytvořte šachovnicovou matici 8x8 pomocí funkce `tile`.


In [30]:
matice1 = np.array([[0, 1], [1, 0]])
matice2 = np.tile(matice1, (4, 4))
print(matice2)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


12. Vytvořte vektor velikosti 10 s hodnotami v rozsahu od 0 do 1 (obě krajní hodnoty vyloučeny).


In [11]:
vector = np.linspace(0, 1, 12)[1:-1]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


13. Vytvořte strukturované pole s koordináty `x` a `y` pokrývající oblast `[0, 1] x [0, 1]`.


In [12]:
grid_size = 5
struct_array = np.zeros((grid_size, grid_size), [('x', float), ('y', float)])
x_coords, y_coords = np.meshgrid(np.linspace(0, 1, grid_size), np.linspace(0, 1, grid_size))
struct_array['x'] = x_coords
struct_array['y'] = y_coords
print(struct_array[:2, :2])

[[(0.  , 0.  ) (0.25, 0.  )]
 [(0.  , 0.25) (0.25, 0.25)]]


## 1.3 NumPy a práce se soubory

1. Jak načíst následující soubor?
```
1, 2, 3, 4, 5
6, , , 7, 8
, , 9, 10, 11
```


In [18]:
%%writefile test_data.csv
1, 2, 3, 4, 5
6, , , 7, 8
 , , 9,10,11

Writing test_data.csv


In [19]:
loaded_data = np.genfromtxt('test_data.csv', delimiter=',')
print(loaded_data)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


2. Vytvořte tři náhodné matice 5x5 a uložte je do souboru ve formátu HDF5.


In [14]:
import h5py

In [16]:
mat1 = np.random.rand(5, 5)
mat2 = np.random.rand(5, 5)
mat3 = np.random.rand(5, 5)\

with h5py.File('matice.h5', 'w') as hdf_file:
    hdf_file.create_dataset('matrix_1', data=mat1)
    hdf_file.create_dataset('matrix_2', data=mat2)
    hdf_file.create_dataset('matrix_3', data=mat3)

3. Načtěte soubor z předchozího úkolu, zobrazte obsah každé matice a zjistěte jejich rozměry.


In [17]:
with h5py.File('matice.h5', 'r') as hdf_file:
    for key in hdf_file.keys():
        loaded_data = hdf_file[key][:]
        print(key)
        print(loaded_data.shape)
        print(loaded_data)

matrix_1
(5, 5)
[[0.22395458 0.92926005 0.28425253 0.40075275 0.64256596]
 [0.62219914 0.91738472 0.41998884 0.04055795 0.13031852]
 [0.62603752 0.74744388 0.68809005 0.3012081  0.53200304]
 [0.38039699 0.41130208 0.44643706 0.52302563 0.61347188]
 [0.89359269 0.9012847  0.08350068 0.31073085 0.16641638]]
matrix_2
(5, 5)
[[0.75499452 0.92247172 0.20852797 0.65121951 0.1203298 ]
 [0.47291905 0.07250202 0.45171684 0.43007849 0.87963405]
 [0.16673407 0.0521886  0.23621152 0.13868973 0.18066322]
 [0.73832434 0.2024743  0.5780876  0.07744956 0.30787731]
 [0.69771167 0.7809161  0.55672802 0.08228824 0.37586272]]
matrix_3
(5, 5)
[[0.9657654  0.33822641 0.59556673 0.11369625 0.17136494]
 [0.30133882 0.70594047 0.41421797 0.50486908 0.60009864]
 [0.28356508 0.32878724 0.714193   0.64168409 0.56551242]
 [0.62672533 0.6088514  0.14012913 0.08899396 0.47975817]
 [0.03789273 0.81677697 0.76361596 0.62709803 0.59073688]]
