# 1. Úkoly

## 1.1 Indexování a řezání

- Vytvořte NumPy pole s názvem `a` obsahující čísla od 1 do 10.
- Vytvořte 2D NumPy pole s názvem `b` o rozměrech 3x3 a naplňte ho libovolnými čísly.


In [3]:
import numpy as np

In [2]:
a = np.arange(1, 11)
b = np.random.randint(1, 20, size=(3,3))
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[[14 14  6]
 [14  1 11]
 [ 8  5 19]]


1. Vyberte z pole `a` třetí a čtvrtý prvek.

In [3]:
a[2:4]

array([3, 4])

2. Vyberte z pole `a` všechna sudá čísla.

In [4]:
a[a % 2 == 0]

array([ 2,  4,  6,  8, 10])

3. Obraťte vektor `a` (první prvek se stane posledním).

In [6]:
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

4. Vyberte z pole `b` druhý řádek.

In [7]:
b[1, :]

array([14,  1, 11], dtype=int32)

5. Vyberte z pole `b` diagonální prvky.

In [8]:
np.diag(b)

array([14,  1, 19], dtype=int32)

6. Změňte hodnotu prvku na druhém řádku, prvním sloupci v `b` na 100.

In [10]:
b[1, 0] = 100
b

array([[ 14,  14,   6],
       [100,   1,  11],
       [  8,   5,  19]], dtype=int32)

7. Vyberte z pole `b` všechny prvky větší než 5.

In [11]:
b[b > 5]

array([ 14,  14,   6, 100,  11,   8,  19], dtype=int32)

8. Vytvořte masku pro pole `b`, která bude `True` pro všechny prvky menší než 3.

In [12]:
maska = b < 3
print(maska)

[[False False False]
 [False  True False]
 [False False False]]


9. Pomocí masky vyberte z pole `b` všechny prvky menší než 3.

In [13]:
b[maska]

array([1], dtype=int32)

## 1.2 View a copy

- Vytvořte NumPy pole s názvem `a` a naplňte ho libovolnými čísly.


In [14]:
a = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

1. Pomocí `a` vytvořte proměnnou `b` obsahující řez druhého řádku a všech sloupců pole `a`.

In [15]:
b = a[1, :]
b

array([4, 5, 6])

2. Změňte hodnotu prvního prvku v `b`. Jak se tato změna projeví v `a`?

In [17]:
b[0] = 100
print(a)

[[  1   2   3]
 [100   5   6]
 [  7   8   9]]


3. Vytvořte proměnnou `c` obsahující **kopii** druhého řádku pole `a`.

In [18]:
c = a[1, :].copy()
c

array([100,   5,   6])

4. Změňte hodnotu prvního prvku v `c`. Jak se tato změna projeví v `a`?

In [19]:
c[0] = 99
print(a)

[[  1   2   3]
 [100   5   6]
 [  7   8   9]]


5. Zjistěte, zda `b` a `c` sdílí stejná data v paměti.

In [20]:
np.shares_memory(b, c)

False

6. Vytvořte proměnnou `d` obsahující diagonální prvky pole `a`.

In [21]:
d = np.diagonal(a)
d

array([1, 5, 9])

7. Změňte hodnotu prvního diagonálního prvku v `d`. Jak se tato změna projeví v `a`?

In [23]:
d = np.diag(a).copy()
d[0] = 111
print(d)
print(a)

[111   5   9]
[[  1   2   3]
 [100   5   6]
 [  7   8   9]]


8. Vytvořte proměnnou `e` obsahující transpozici pole `a`. Ověřte přes atribut `base`, zda jde o kopii, nebo o `view`.

In [24]:
e = a.T
print(np.shares_memory(a, e))
print(e.base is a)

True
True


## 1.3 Lineární algebra

1. Vynásobte matici 5x3 maticí 3x2 (maticový součin).


In [25]:
A = np.random.rand(5, 3)
B = np.random.rand(3, 2)
C = A @ B 
C

array([[0.79267911, 0.49250439],
       [1.44334135, 0.92645228],
       [0.29454129, 0.26865201],
       [1.07893321, 0.68607916],
       [1.20726468, 0.58161684]])

2. Vezměte náhodnou matici 10x2 představující kartézské souřadnice a převeďte je na polární souřadnice.

In [26]:
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y, X)
print(R)
print(T)

[0.993603   1.02798489 0.66240789 0.85538413 1.14262861 0.58832981
 1.0921336  0.74118283 0.43078114 1.10993269]
[0.59058909 0.34106696 0.24699744 0.25574847 0.71645778 1.32162416
 0.90610313 0.02660801 0.20592422 1.12091639]


3. Pro dvě pole `X` a `Y` zkonstruujte Cauchyho matici `C` (`C_ij = 1 / (x_i - y_j)`).

In [27]:
X = np.arange(5)
Y = X + 0.5
C = 1.0 / (X[:, np.newaxis] - Y)
C

array([[-2.        , -0.66666667, -0.4       , -0.28571429, -0.22222222],
       [ 2.        , -2.        , -0.66666667, -0.4       , -0.28571429],
       [ 0.66666667,  2.        , -2.        , -0.66666667, -0.4       ],
       [ 0.4       ,  0.66666667,  2.        , -2.        , -0.66666667],
       [ 0.28571429,  0.4       ,  0.66666667,  2.        , -2.        ]])

4. Uvažujte náhodné pole tvaru `(100, 2)` reprezentující souřadnice a spočítejte vzdálenost pro každý bod.

In [5]:
from scipy.spatial.distance import cdist

In [4]:
Z = np.random.random((100, 2))
D = cdist(Z, Z)
print(D.shape)

(100, 100)


5. Ověřte empiricky na náhodných maticích, že platí $(AB)^T = B^T A^T$.

In [29]:
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

leva_strana = (A @ B).T
prava_strana = B.T @ A.T

np.allclose(leva_strana, prava_strana)

True

6. Pro náhodné 1D vektory $u, v$ vypočítejte dyadický součin $uv$, kde $$(uv)_{ij} = u_i v_j$$, pomocí `newaxis`. Zkontrolujte výsledek s `np.outer(u, v)`.

In [31]:
u = np.random.rand(5)
v = np.random.rand(5)

vysledek = u[:, np.newaxis] * v
kontrola = np.outer(u, v)

np.allclose(vysledek, kontrola)

True

7. Vypočítejte hodnost matice o velikosti 5x6 naplněné hodnotami 0, 1, 2, 3 ... Byli byste schopni zdůvodnit, proč je hodnost právě taková?

In [32]:
M = np.arange(30).reshape(5, 6)
hodnost = np.linalg.matrix_rank(M)
print(hodnost)

2


## 1.4 Funkce nad poli

1. Vytvořte pole 10x10 s náhodnými hodnotami a najděte minimální a maximální hodnoty.

In [6]:
Z = np.random.random((10, 10))
print(Z.min())
print(Z.max())

0.00038084470406329896
0.9969822518576545


2. Vytvořte náhodný vektor o velikosti 30 a najděte střední hodnotu.

In [7]:
Z = np.random.random(30)
print(Z.mean())

0.4500812516470212


3. Uvažujme celočíselný vektor `Z`. Které z těchto výrazů jsou platné?
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [8]:
Z = np.arange(5)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


4. Jaký je výsledek následujícího výrazu?
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [10]:
print(0 * np.nan) # nan
print(np.nan == np.nan) # False
print(np.inf > np.nan) # False
print(np.nan - np.nan) # nan
print(np.nan in set([np.nan])) # True
print(0.3 == 3 * 0.1)  # False

nan
False
False
nan
True
False


5. Jaké jsou výsledky následujících výrazů?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [11]:
import warnings

In [12]:
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    print(np.array(0) / np.array(0)) # nan
    print(np.array(0) // np.array(0)) # 0
    
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


C:\Users\Diana\AppData\Local\Temp\ipykernel_14096\2719092011.py:6: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


6. Jak najít společné (stejné) hodnoty mezi dvěma poli?

In [13]:
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)
np.intersect1d(Z1, Z2)

array([0, 2, 3, 5, 7], dtype=int32)

7. Jak vypočítat `((A+B) * (-A/2))` přímo v poli (bez kopírování)?

In [14]:
A = np.ones(3)*1
B = np.ones(3)*2

np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

8. Vytvořte náhodný vektor o velikosti 10 a seřaďte ho.

In [15]:
Z = np.random.random(10)
Z.sort()
Z

array([0.09604984, 0.09746681, 0.2207313 , 0.33505996, 0.67501434,
       0.6838197 , 0.68400897, 0.69174851, 0.73981348, 0.92219882])

9. Vezměte daný vektor: jak přidat 1 ke každému prvku indexovanému druhým vektorem (pozor na opakované indexy)?

In [16]:
Z = np.zeros(10)
I = np.random.randint(0, len(Z), 20)

np.add.at(Z, I, 1)
print(Z)

[2. 2. 2. 2. 2. 1. 1. 2. 2. 4.]
